// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvic9sboH1BNt30i2escNmWWKB68Pnzrw',
    appId: '1:963857614340:web:54c79174551a14b78c9751',
    messagingSenderId: '963857614340',
    projectId: 'oxytrack-2026',
    authDomain: 'oxytrack-2026.firebaseapp.com',
    databaseURL: 'https://oxytrack-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oxytrack-2026.firebasestorage.app',
    measurementId: 'G-1DF5P4EYCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedL0CHxs5iQlUjlWCuaL0kNAzgA7qBSw',
    appId: '1:963857614340:android:1274603f0b87f9e08c9751',
    messagingSenderId: '963857614340',
    projectId: 'oxytrack-2026',
    databaseURL: 'https://oxytrack-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oxytrack-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByswtJ6568yFlh9j977FpcUaSjzZfJUbU',
    appId: '1:963857614340:ios:a4908f63866659518c9751',
    messagingSenderId: '963857614340',
    projectId: 'oxytrack-2026',
    databaseURL: 'https://oxytrack-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oxytrack-2026.firebasestorage.app',
    iosBundleId: 'com.example.pulseguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByswtJ6568yFlh9j977FpcUaSjzZfJUbU',
    appId: '1:963857614340:ios:a4908f63866659518c9751',
    messagingSenderId: '963857614340',
    projectId: 'oxytrack-2026',
    databaseURL: 'https://oxytrack-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oxytrack-2026.firebasestorage.app',
    iosBundleId: 'com.example.pulseguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvic9sboH1BNt30i2escNmWWKB68Pnzrw',
    appId: '1:963857614340:web:e436061cf27492a88c9751',
    messagingSenderId: '963857614340',
    projectId: 'oxytrack-2026',
    authDomain: 'oxytrack-2026.firebaseapp.com',
    databaseURL: 'https://oxytrack-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oxytrack-2026.firebasestorage.app',
    measurementId: 'G-QBTJH35836',
  );
}
